# -*- coding: utf-8 -*-
"""DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yYQPFAbrb0EiaAB54prLpqTWID5IhIOl
"""

import pandas as pd

df = pd.read_csv("food_delivery_analytics_cleaned.csv")

print(df.shape)
print(df.info())
print(df.isnull().sum())
print(df.describe())

print(df.head())
print(df.columns)

df.duplicated().sum()

df.isnull().sum()

df.nunique()

print(df.columns.tolist())

print(df.columns.tolist())

df['Revenue'] = (
    df['order_value']
    + df['delivery_fee']
    + df['tip_amount']
)

df['Discount_Amount'] = (
    df['order_value'] * df['discount_amount'] / 100
)

df.shape[0]

df['order_value'].mean()

df['discount_percentage'] = (
    df['discount_amount'] / df['order_value']
) * 100

df['delivery_delay_minutes'] = (
    df['delivery_time_minutes'] - df['estimated_delivery_time']
)

df['delivery_status'] = df['delayed_delivery_flag'].map({
    0: 'On Time',
    1: 'Delayed'
})

df['customer_type'] = df['premium_customer_flag'].map({
    0: 'Regular',
    1: 'Premium'
})

total_revenue = df['final_amount_paid'].sum()

print("Total Revenue:", total_revenue)

total_orders = df['order_id'].nunique()

print("Total Orders:", total_orders)

avg_order_value = df['final_amount_paid'].mean()

print("Average Order Value:", avg_order_value)

print(df['customer_rating'].mean())

print(df['delivery_time_minutes'].mean())

df.groupby('city_tier')['order_id'].count()

df.groupby('city_tier')['final_amount_paid'].sum()

df.groupby('order_month')['order_id'].count()

df.groupby('order_month')['final_amount_paid'].sum()

df.groupby('customer_type').agg(
    Orders=('order_id', 'count'),
    Revenue=('final_amount_paid', 'sum'),
    Avg_Order_Value=('final_amount_paid', 'mean'),
    Avg_Rating=('customer_rating', 'mean')
)

df.groupby('traffic_level_score')['delivery_time_minutes'].mean()

df.groupby('traffic_level_score')['delayed_delivery_flag'].mean() * 100

df.groupby('weather_severity_score')['delivery_time_minutes'].mean()

df.groupby('delivery_distance_km')['delivery_time_minutes'].mean()

cancellation_rate = df['cancellation_flag'].mean() * 100

print("Cancellation Rate:", cancellation_rate)

df.groupby('premium_customer_flag')['cancellation_flag'].mean() * 100

df.groupby('city_tier')['cancellation_flag'].mean() * 100

df.groupby('delivery_status')['customer_rating'].mean()

df.groupby('delivery_partner_rating')['customer_rating'].mean()

df.groupby('restaurant_rating')['customer_rating'].mean()

import matplotlib.pyplot as plt

monthly_revenue = df.groupby('order_month')['final_amount_paid'].sum()

monthly_revenue.plot(kind='bar')

plt.title('Monthly Revenue')
plt.xlabel('Month')
plt.ylabel('Revenue')
plt.show()

plt.scatter(
    df['delivery_distance_km'],
    df['delivery_time_minutes']
)

plt.title('Delivery Time vs Distance')
plt.xlabel('Delivery Distance (km)')
plt.ylabel('Delivery Time (minutes)')
plt.show()

plt.scatter(
    df['delivery_distance_km'],
    df['delivery_time_minutes']
)

plt.title('Delivery Time vs Distance')
plt.xlabel('Delivery Distance (km)')
plt.ylabel('Delivery Time (minutes)')
plt.show()

df.groupby('traffic_level_score')['delivery_time_minutes'].mean().plot(
    kind='bar'
)

plt.title('Traffic Level vs Delivery Time')
plt.xlabel('Traffic Level')
plt.ylabel('Average Delivery Time')
plt.show()

df['customer_type'] = df['premium_customer_flag'].map({
    False: 'Regular',
    True: 'Premium'
})

df.groupby('customer_type')['final_amount_paid'].sum().plot(
    kind='bar')
plt.title('Revenue: Premium vs Regular Customers')
plt.xlabel('Customer Type')
plt.ylabel('Revenue')
plt.show()